package com.movie.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Movie")

public class Movie {
    private String imdb_title_id;
    private String title;
    private String original_title;
    private String year;
    private String date_published;
    private String genre;
    private String duration;
    private String country;
    private String language;
    private String director;
    private String writer;
    private String production_company;
    private String actors;
    private String description;
    private String avg_vote;
    private String votes;
    private String budget;
    private String usa_gross_income;
    private String worlwide_gross_income;
    private String metascore;
    private int reviews_from_users;
    private String reviews_from_critics;

    //setter and getter methods
    public String getImdbTitleId() {
        return imdb_title_id;
    }

    public void setImdbTitleId(String imdbTitleId) {
        this.imdb_title_id = imdbTitleId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getOriginalTitle() {
        return original_title;
    }

    public void setOriginalTitle(String originalTitle) {
        this.original_title = originalTitle;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getDatePublished() {
        return date_published;
    }

    public void setDatePublished(String datePublished) {
        this.date_published = datePublished;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public String getDuration() {
        return duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getDirector() {
        return director;
    }

    public void setDirector(String director) {
        this.director = director;
    }

    public String getWriter() {
        return writer;
    }

    public void setWriter(String writer) {
        this.writer = writer;
    }

    public String getProductionCompany() {
        return production_company;
    }

    public void setProductionCompany(String productionCompany) {
        this.production_company = productionCompany;
    }

    public String getActors() {
        return actors;
    }

    public void setActors(String actors) {
        this.actors = actors;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getAverageVote() {
        return avg_vote;
    }

    public void setAverageVote(String averageVote) {
        this.avg_vote = averageVote;
    }

    public String getVotes() {
        return votes;
    }

    public void setVotes(String votes) {
        this.votes = votes;
    }

    public String getBudget() {
        return budget;
    }

    public void setBudget(String budget) {
        this.budget = budget;
    }

    public String getUsaGrossIncome() {
        return usa_gross_income;
    }

    public void setUsaGrossIncome(String usaGrossIncome) {
        this.usa_gross_income = usaGrossIncome;
    }
    public String getWorlwide_gross_income() {
        return worlwide_gross_income;
    }

    public void setWorlwideGrossIncome(String worlwideGrossIncome) {
        this.worlwide_gross_income = worlwideGrossIncome;
    }

    public String getMetascore() {
        return metascore;
    }

    public void setMetascore(String metascore) {
        this.metascore = metascore;
    }

    public int getReviewsFromUsers() {
        return reviews_from_users;
    }

    public void setReviewsFromUsers(int reviewsFromUsers) {
        this.reviews_from_users = reviewsFromUsers;
    }

    public String getReviewsFromCritics() {
        return reviews_from_critics;
    }

    public void setReviewsFromCritics(String reviewsFromCritics) {
        this.reviews_from_critics = reviewsFromCritics;
    }
}

